### ISSUE TITLE
Linking username/password input fields to script

### ISSUE THREAD

**Issue by JoshuaFrancisco** [CSCI-150-Team-3/MultiplayerGalaga#23]
On the login_menu scene I have a script (Login) in the Canvas object where i need to link InputUsername, InputPassword and LoginButton to the input fields, I am able to link LoginButton but not the username/password 

![123](https://user-images.githubusercontent.com/54962494/69135526-18faee80-0a6e-11ea-9528-067f3d190469.png)

**Comment by Hannsel101** [comment]
Since we are using textmeshpro for the text inputs and buttons you would require to add "using TMPro" in the preprocessors directives. And you can call the object as TMP_InputField, after that the commands are similar to normal input field objects

**Comment by JoshuaFrancisco** [comment]
i added the libary TMPro and changed my InputField to TMP_InputField, and it worked! I am able to input a username and password, click on login and unity successfully connects to my database

**Comment by JoshuaFrancisco** [comment]
i added the libary TMPro and changed my InputField to TMP_InputField, and it worked! I am able to input a username and password, click on login and unity successfully connects to my database
